### ISSUE TITLE
App screen flashing or flickering right after every form dismissal

### ISSUE THREAD

**Issue by ajith-heb** [medallia/digital-ios-sdk#10]
SDK Version: 4.3.0
Xcode Version: 15.1

OS Version: 17.2

Description:
App screen is flashing or flickering just after Medallia form is dismissed in the app.

Steps to Reproduce
1. Show any form from the app screen.
2. Submit any sample form and wait for form to dismiss or Click close button to dismiss the form

Expected Behavior
Screen should not flicker after dismissing the form. I hope this is caused by some animations inside the SDK.

Actual Behavior
Screen flickering right after Medallia form is dismissed which gives a bad user experience.

Code Snippet 

MedalliaDigital.showForm(formID, success: {
           
        }) { (error) in
  }

**Comment by OriMedallia** [comment]
Hi,

Please contact your Digital Expert with all the information including a video of the issue.
In addition please try to reproduce the issue on a sample app or an empty project.
Once the Digital Expert raises a ticket, we'll be able to prioritize it.

Thanks,
Ori

**Comment by Marc-Azevedo** [comment]
This is still happening on the latest version (4.5.1)

**Comment by OriMedallia** [comment]
Fixed on 4.6

**Comment by ajith-heb** [comment]
> This is still happening on the latest version (4.5.1)

@Marc-Azevedo did you get a chance to verify the fix in latest 4.6.0 version? I've still that problem exists in latest version.

**Comment by Marc-Azevedo** [comment]
@ajith-heb Yeah. It just fixed the issue if we tap to go back. If we complete the survey the flickering stills happens.

**Comment by ajith-heb** [comment]
I was able to reproduce the issue intermittently in both scenarios (while dismissing the modal after clicking the close button and the dismissal after submit click)
