### ISSUE TITLE
Wrong name of XCFramework/package?

### ISSUE THREAD

**Issue by cheif** [medallia/Digital-iOS-SDK#2]
Hi!

I just tried using this to integrate Medallia, but when I try to add this as a dependency I get the error `artifact not found for target 'MedalliaPackage'`. Having worked a bit with SPM I suspect this is because the package is named `MedalliaPackage` but the bundled `.xcframework` is called `MedalliaDigitalSDK`, I think they need to be the same.
`

**Comment by alex-taffe** [comment]
I'm having the same issue, based on [this](https://support.zendesk.com/hc/en-us/community/posts/4429572484762-Xcode-13-3-Beta-3-artifact-not-found-for-target) post, your theory seems to be the case

**Comment by OriMedallia** [comment]
Hi @cheif  and @alex-taffe ,

Thanks for reporting this issue.
We've fixed the issue but you'll have to delete the MedalliaPackage and clear the Swift Package Manager cache on your machine by going to ~/Library/Caches/org.swift.swiftpm/ and delete:
- Digital-iOS-SDK folder
- Digital-iOS-SDK lock file
Then please  reintegrate  with version 4.0.2
