### ISSUE TITLE
(10040) Form is not available

### ISSUE THREAD

**Issue by GRGBISHOW** [medallia/Digital-iOS-SDK#5]
I get "(10040) Form is not available" even I have already published the form in the Medallia portal.
Inputs: All the credentials (APIkey) and formID is correct. Any Help?
Env: Sandbox
Version: 3.10.2

**Comment by OriMedallia** [comment]
Hi @GRGBISHOW 

Please contact your Medallia CSM with all the details.

Thanks,
Ori
