### ISSUE TITLE
Xcode 15 beta - Cycle inside <Target>; building could produce unreliable results.

### ISSUE THREAD

**Issue by swhitty** [medallia/digital-ios-sdk#6]
A large iOS app I maintain fails to build in Xcode 15 beta 1/2.  The project builds fine with Xcode 14.3.1
It fails with the error:

`Cycle inside <Target>; building could produce unreliable results.`

I have narrowed the issue down to the root cause and attached a sample project that reproduces it (Test.zip).

Two steps need to be performed to reproduce the error to a new project:

1. Add the swift package: https://github.com/medallia/digital-ios-sdk.git

2. Add blank build script phase with input files: `$(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)`

When both of these steps are performed then the error occurs. If either of these steps is reverted the issue goes away.

Removing the Swift Package and linking directly to the `MedalliaDigitalSDK.xcframework` works fine with the build script phase and is not impacted.

I am not sure if this points to an issue within the Medallia spm package or Xcode 15 itself but I am raising it here for visibility.

[Test.zip](https://github.com/medallia/digital-ios-sdk/files/11904244/Test.zip)

Raised with Apple FB12477645

**Comment by OriMedallia** [comment]
Hi Simon,
We're not supporting beta versions of Xcode
Once Xcode 15 is GA and the issue is still happening, we'll look into it.
Thanks
