### ISSUE TITLE
Privacy Manifest - Required Reason APIs

### ISSUE THREAD

**Issue by nwelchbauer-disney** [medallia/digital-ios-sdk#9]
Starting Spring 2024, third-party iOS SDKs are required to include PrivacyInfo.xcprivacy manifests detailing reasons for usage of certain privacy-sensitive APIs.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

This SDK should include a PrivacyInfo.xcprivacy.

**Comment by moyerr** [comment]
Is there a timeline for getting the Privacy Manifest added? Our app submissions are now being flagged because this SDK uses the following APIs:

- `fstat`
- `NSFileModificationDate`
- `NSFileSystemFreeSize`
- `NSFileSystemSize`
- `NSUserDefaults`
- `stat`

**Comment by OriMedallia** [comment]
Hi,
Please use v4.0.1 for Privacy Manifest support
Thanks
